name = "ResettableStacks"
uuid = "ae5879a3-cd67-5da8-be7f-38c6eb64a37b"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "1.2.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
JET = "0.9"
StaticArrays = "1.0"
julia = "1.10"

[extras]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "ArrayInterface", "JLArrays", "JET"]
